//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanıcılar
    {
        public int KullanıcıID { get; set; }
        public string KullanıcıAdı { get; set; }
        public string Şifre { get; set; }
        public string EPosta { get; set; }
        public int RoleID { get; set; }
    
        public virtual Tbl_Roller Tbl_Roller { get; set; }
    }
}
